branches:
  only:
    - master
language: node_js
node_js:
  - "12.13.0"
script:
  - echo "Deploy!"
install:
  # - npm install -g firebase-tools
  - npm install firebase-tools
after_success:
  - firebase deploy --project service-worker-playgroun-152cd --token $FIREBASE_TOKEN
